// <auto-generated />
using System;
using EphemerisProvider.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EphemerisProvider.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230430074521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EphemerisProvider.Models.GlonassEphemeris", b =>
                {
                    b.Property<int>("CsSatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EpochTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Af0Hz")
                        .HasColumnType("REAL");

                    b.Property<double>("Af1HzPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("AxEcefKmPerSec2")
                        .HasColumnType("REAL");

                    b.Property<double>("AyEcefKmPerSec2")
                        .HasColumnType("REAL");

                    b.Property<double>("AzEcefKmPerSec2")
                        .HasColumnType("REAL");

                    b.Property<int>("FrequencyLitera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrbitPointId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VxEcefKmPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("VyEcefKmPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("VzEcefKmPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("XEcefKm")
                        .HasColumnType("REAL");

                    b.Property<double>("YEcefKm")
                        .HasColumnType("REAL");

                    b.Property<double>("ZEcefKm")
                        .HasColumnType("REAL");

                    b.HasKey("CsSatNumber", "EpochTimeUtc");

                    b.ToTable("GlonassEphemerides");
                });
#pragma warning restore 612, 618
        }
    }
}
